variables:
  GIT_STRATEGY: clone
  GIT_CLEAN_FLAGS: none

stages:
  - build
  - backup
  - test
  - deploy

before_script:
  - echo "Checking static/popup-login.html..."
  - '[ -d static/popup-login.html ] && echo "Found directory instead of file. Removing it..." && rm -rf static/popup-login.html || echo "No directory to clean."'

build-be:
  stage: build
  tags: [deploy]
  script:
    - docker-compose -f docker-compose.backend.yml build backend
  rules:
    - if: '$CI_COMMIT_BRANCH =~ /^(be-dev|main|master)$/'

build-data:
  stage: build
  tags: [deploy]
  script:
    - docker-compose -f docker-compose.data.yml build data
  rules:
    - if: '$CI_COMMIT_BRANCH =~ /^(data-dev|main|master)$/'

build-fe:
  stage: build
  tags: [deploy]
  script:
    - echo "VITE_APP_API_URL=$VITE_APP_API_URL" > frontend/.env.production
    - docker build --no-cache -t frontend:ci -f frontend/Dockerfile ./frontend
    - docker create --name frontend-builder frontend:ci
    - rm -rf frontend/dist
    - mkdir -p frontend/dist
    - docker cp frontend-builder:/app/dist/. ./frontend/dist/
    - docker rm frontend-builder

  rules:
    - if: '$CI_COMMIT_BRANCH =~ /^(fe-dev|main|master)$/'
    
backup-db:
  stage: backup
  tags: [deploy]
  script:
  script:
    - mkdir -p ci-backup
    - docker exec db pg_dump -U ssafy -d app > db-backup.sql
    - tar czf db-backup.tar.gz db-backup.sql
    - mv db-backup.tar.gz ci-backup/
  artifacts:
    paths:
      - ci-backup/db-backup.tar.gz
    expire_in: 1 week
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'
    - if: '$CI_COMMIT_BRANCH == "master"'
    
integration-test:
  stage: test
  tags: [deploy]
  needs:
    - build-be
    - build-fe
    - build-data
    - backup-db
  script:
    - docker-compose -f docker-compose.ci.yml down --remove-orphans || true
    - tar xzf ci-backup/db-backup.tar.gz
    - docker-compose -f docker-compose.ci.yml up -d db redis
    - |
      for i in {1..10}; do echo "db healthcheck... ($i/10)"; docker exec db pg_isready -U ssafy && break || sleep 3; done
    - docker exec -i db psql -U ssafy -d app < db-backup.sql
    - docker-compose -f docker-compose.ci.yml up -d backend data frontend caddy
    - docker restart caddy
    - |
      for i in {1..10}; do echo "data healthcheck... ($i/10)"; curl -sSf http://localhost:8000/data/api/v1/health && break || sleep 3; done || (echo "data healthcheck failed" && docker logs backend && exit 1)
    - |
      for i in {1..10}; do echo "backend healthcheck... ($i/10)"; curl -sSf http://localhost:4000/health && break || sleep 3; done || (echo "backend healthcheck failed" && docker logs backend && exit 1)
    - |
      for i in {1..10}; do echo "frontend healthcheck... ($i/10)"; curl -sSf http://localhost && break || sleep 3; done || (echo "frontend healthcheck failed" && docker logs caddy && exit 1)
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'
    - if: '$CI_COMMIT_BRANCH == "master"'

deploy:
  stage: deploy
  tags: [deploy]
  script:
    - docker-compose -f docker-compose.ci.yml down --remove-orphans || true
    - docker-compose -f docker-compose.ci.yml up -d
    - docker restart caddy
    - |
      for i in {1..10}; do echo "data healthcheck... ($i/10)"; curl -sSf https://www.souffle.kr/data/api/v1/health && break || sleep 3; done || (echo "data healthcheck failed" && docker logs data && exit 1)
    - |
      for i in {1..10}; do echo "backend healthcheck... ($i/10)"; curl -sSf https://www.souffle.kr/health && break || sleep 3; done || (echo "backend healthcheck failed" && docker logs backend && exit 1)
    - |
      for i in {1..10}; do echo "frontend healthcheck... ($i/10)"; curl -sSf https://www.souffle.kr && break || sleep 3; done || (echo "frontend healthcheck failed" && docker logs caddy && exit 1)
  rules:
    - if: '$CI_COMMIT_BRANCH == "master"'
