variables:
  GIT_STRATEGY: fetch
  GIT_CLEAN_FLAGS: none

stages:
  - build
  - test
  - deploy

build-be:
  stage: build
  tags: [deploy]
  script:
    - docker-compose -f docker-compose.backend.yml build backend
  rules:
    - if: '$CI_COMMIT_BRANCH =~ /^(be-mvp|main|master)$/'

build-data:
  stage: build
  tags: [deploy]
  script:
    - docker-compose -f docker-compose.data.yml build data
  rules:
    - if: '$CI_COMMIT_BRANCH =~ /^(data-dev|main|master)$/'

build-fe:
  stage: build
  tags: [deploy]
  script:
    - docker-compose -f docker-compose.frontend.yml build frontend
  rules:
    - if: '$CI_COMMIT_BRANCH =~ /^(fe-dev|main|master)$/'

integration-test:
  stage: test
  tags: [deploy]
  needs:
    - build-be
    - build-fe
    - build-data
  script:
    - docker-compose -f docker-compose.ci.yml down --volumes --remove-orphans || true
    - docker-compose -f docker-compose.ci.yml up -d
    - |
      curl -sSf http://localhost:8000/ || (docker logs data && exit 1)
    - |
      for i in {1..10}; do echo "backend 헬스체크 대기 중... ($i/10)"; curl -sSf http://localhost:4000/health && break || sleep 3; done || (echo "backend 헬스체크 실패" && docker logs backend && exit 1)

    - |
      curl -sSf http://localhost:3000/ || (docker logs frontend && exit 1)
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'
    - if: '$CI_COMMIT_BRANCH == "master"'

deploy:
  stage: deploy
  tags: [deploy]
  script:
    - docker-compose -f docker-compose.yml down --volumes --remove-orphans || true
    - docker-compose -f docker-compose.yml up -d
    - |
      curl -sSf https://www.souffle.kr/ || (docker logs data && exit 1)
    - |
      for i in {1..10}; do echo "backend 헬스체크 대기 중... ($i/10)"; curl -sSf https://www.souffle.kr/health && break || sleep 3; done || (echo "backend 헬스체크 실패" && docker logs backend && exit 1)

    - |
      curl -sSf https://www.souffle.kr || (docker logs frontend && exit 1)
  rules:
    - if: '$CI_COMMIT_BRANCH == "master"'
