services:
  frontend:
    build: ./frontend
    container_name: frontend
      #    ports:
      #      - "3000:3000"
    restart: always
      #    depends_on:
      #      backend:
      #        condition: service_healthy
          #    environment:
          #      - NODE_ENV=production
    # env_file:
    #   - ./frontend/.env
    environment:
      VITE_APP_API_URL: ${VITE_APP_API_URL}
    networks:
      - public

networks:
  public:
  internal:
